name:                advent-of-code
version:             0.1.0.0
github:              "jahaynes/advent-of-code-2023"
license:             BSD-3-Clause

dependencies:
- base
- bytestring
- containers
- regex-tdfa
- split
- text
- vector
- vector-algorithms

default-extensions:
- BangPatterns
- DeriveGeneric
- InstanceSigs
- LambdaCase
- OverloadedStrings

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src/Common

executables:

  day01:
    main:           Main.hs
    source-dirs:    src/Day01
    dependencies:   advent-of-code

  day02:
    main:           Main.hs
    source-dirs:    src/Day02
    dependencies:   advent-of-code

  day03:
    main:           Main.hs
    source-dirs:    src/Day03
    dependencies:   advent-of-code

  day04:
    main:           Main.hs
    source-dirs:    src/Day04
    dependencies:   advent-of-code

  day05:
    main:           Main.hs
    source-dirs:    src/Day05
    dependencies:   advent-of-code

  day06:
    main:           Main.hs
    source-dirs:    src/Day06
    dependencies:   advent-of-code

  day07:
    main:           Main.hs
    source-dirs:    src/Day07
    dependencies:   advent-of-code

  day08:
    main:           Main.hs
    source-dirs:    src/Day08
    dependencies:   advent-of-code

  day09:
    main:           Main.hs
    source-dirs:    src/Day09
    dependencies:   advent-of-code
